import InfoBar from "@/components/InfoBar";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={inter.className}>
      <body>
        <InfoBar />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
